---
title: "Model comparison (baseline scenario)"
author: "Christophe Nozaradan"
date: "January 2022"
output: html_document
---

```{css, echo=FALSE}
.main-container {
  max-width: 1200px; 
}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
options(dplyr.summarise.inform = FALSE)
options(warn = -1)
```
## Extraction via web scraping 
We first extract the data from the simulation results stored in HTML output.

```{r}
library(tidyverse)
library(rvest)
library(scales)
rep <- './run-2/'
files <- list.files(path = rep,pattern = ".html")

settlements <- list()
payments <- list()
sizes <- list()

for(i in seq_along(files)) {

  page <- read_html(paste0(rep,files[i]))

  # settlement

  settlements[i] <- page %>% html_node(xpath = '//*[@id="evaluating-the-predictive-performance-of-the-chain-ladder-model-and-the-hierarchical-glm-and-gbm"]/pre[2]/code/text()') %>% html_text()
  settlements[i] <- regmatches(settlements[[i]], gregexpr("[[:digit:]]+.[[:digit:]]+", settlements[[i]]))

  # payment

  payments[i] <- page %>% html_node(xpath = '//*[@id="evaluating-the-predictive-performance-of-the-chain-ladder-model-and-the-hierarchical-glm-and-gbm"]/pre[4]/code/text()') %>% html_text()
  payments[i] <- regmatches(payments[i], gregexpr("[[:digit:]]+.[[:digit:]]+", payments[i]))

  # size

  sizes[i] <- page %>% html_node(xpath = '//*[@id="evaluating-the-predictive-performance-of-the-chain-ladder-model-and-the-hierarchical-glm-and-gbm"]/pre[6]/code/text()') %>% html_text()
  sizes[i] <- regmatches(sizes[i], gregexpr("[[:digit:]]+.[[:digit:]]+", sizes[i]))

}

df.settle <- as.data.frame(do.call(rbind, settlements))
names(df.settle) <- c('Actual','CL','HGLM','HGBM','HXGB','HDNN','HCANN')

df.pay <- as.data.frame(do.call(rbind, payments))
names(df.pay) <- c('Actual','CL','HGLM','HGBM','HXGB','HDNN','HCANN')

df.size <- as.data.frame(do.call(rbind, sizes))
names(df.size) <- c('Actual','CL','HGLM','HGBM','HXGB','HDNN','HCANN')
```

## Comparison
We then compute the average relative error for settlement, payment and size:
```{r}
df.settle <- df.settle %>% mutate(error.cl=abs(as.numeric(Actual)-as.numeric(CL))/as.numeric(Actual))
df.settle <- df.settle %>% mutate(error.hglm=abs(as.numeric(Actual)-as.numeric(HGLM))/as.numeric(Actual))
df.settle <- df.settle %>% mutate(error.hgbm=abs(as.numeric(Actual)-as.numeric(HGBM))/as.numeric(Actual))
df.settle <- df.settle %>% mutate(error.hxgb=abs(as.numeric(Actual)-as.numeric(HXGB))/as.numeric(Actual))
df.settle <- df.settle %>% mutate(error.hdnn=abs(as.numeric(Actual)-as.numeric(HDNN))/as.numeric(Actual))
df.settle <- df.settle %>% mutate(error.hcann=abs(as.numeric(Actual)-as.numeric(HCANN))/as.numeric(Actual))

settl.error.cl <- df.settle %>% summarize(av.error=mean(error.cl)) %>% pull(av.error)
settl.error.hglm <- df.settle %>% summarize(av.error=mean(error.hglm)) %>% pull(av.error)
settl.error.hgbm <- df.settle %>% summarize(av.error=mean(error.hgbm)) %>% pull(av.error)
settl.error.hxgb <- df.settle %>% summarize(av.error=mean(error.hxgb)) %>% pull(av.error)
settl.error.hdnn <- df.settle %>% summarize(av.error=mean(error.hdnn)) %>% pull(av.error)
settl.error.hcann <- df.settle %>% summarize(av.error=mean(error.hcann)) %>% pull(av.error)

# Print Results
c('Chain-Ladder' = settl.error.cl, 'Hierarchical GLM' = settl.error.hglm, 'Hierarchical GBM' = settl.error.hgbm, 'Hierarchical XGB' = settl.error.hxgb, 'Hierarchical DNN' = settl.error.hdnn, 'Hierarchical CANN' = settl.error.hcann)

```

```{r}
df.pay <- df.pay %>% mutate(error.cl=abs(as.numeric(Actual)-as.numeric(CL))/as.numeric(Actual))
df.pay <- df.pay %>% mutate(error.hglm=abs(as.numeric(Actual)-as.numeric(HGLM))/as.numeric(Actual))
df.pay <- df.pay %>% mutate(error.hgbm=abs(as.numeric(Actual)-as.numeric(HGBM))/as.numeric(Actual))
df.pay <- df.pay %>% mutate(error.hxgb=abs(as.numeric(Actual)-as.numeric(HXGB))/as.numeric(Actual))
df.pay <- df.pay %>% mutate(error.hdnn=abs(as.numeric(Actual)-as.numeric(HDNN))/as.numeric(Actual))
df.pay <- df.pay %>% mutate(error.hcann=abs(as.numeric(Actual)-as.numeric(HCANN))/as.numeric(Actual))

payment.error.cl <- df.pay %>% summarize(av.error=mean(error.cl)) %>% pull(av.error)
payment.error.hglm <- df.pay %>% summarize(av.error=mean(error.hglm)) %>% pull(av.error)
payment.error.hgbm <- df.pay %>% summarize(av.error=mean(error.hgbm)) %>% pull(av.error)
payment.error.hxgb <- df.pay %>% summarize(av.error=mean(error.hxgb)) %>% pull(av.error)
payment.error.hdnn <- df.pay %>% summarize(av.error=mean(error.hdnn)) %>% pull(av.error)
payment.error.hcann <- df.pay %>% summarize(av.error=mean(error.hcann)) %>% pull(av.error)

# Print Results
c('Chain-Ladder' = payment.error.cl, 'Hierarchical GLM' = payment.error.hglm, 'Hierarchical GBM' = payment.error.hgbm, 'Hierarchical XGB' = payment.error.hxgb, 'Hierarchical DNN' = payment.error.hdnn, 'Hierarchical CANN' = payment.error.hcann)

```

```{r}
#
df.size <- df.size %>% mutate(error.cl=abs(as.numeric(Actual)-as.numeric(CL))/as.numeric(Actual))
df.size <- df.size %>% mutate(error.hglm=abs(as.numeric(Actual)-as.numeric(HGLM))/as.numeric(Actual))
df.size <- df.size %>% mutate(error.hgbm=abs(as.numeric(Actual)-as.numeric(HGBM))/as.numeric(Actual))
df.size <- df.size %>% mutate(error.hxgb=abs(as.numeric(Actual)-as.numeric(HXGB))/as.numeric(Actual))
df.size <- df.size %>% mutate(error.hdnn=abs(as.numeric(Actual)-as.numeric(HDNN))/as.numeric(Actual))
df.size <- df.size %>% mutate(error.hcann=abs(as.numeric(Actual)-as.numeric(HCANN))/as.numeric(Actual))

size.error.cl <- df.size %>% summarize(av.error=mean(error.cl)) %>% pull(av.error)
size.error.hglm <- df.size %>% summarize(av.error=mean(error.hglm)) %>% pull(av.error)
size.error.hgbm <- df.size %>% summarize(av.error=mean(error.hgbm)) %>% pull(av.error)
size.error.hxgb <- df.size %>% summarize(av.error=mean(error.hxgb)) %>% pull(av.error)
size.error.hdnn <- df.size %>% summarize(av.error=mean(error.hdnn)) %>% pull(av.error)
size.error.hcann <- df.size %>% summarize(av.error=mean(error.hcann)) %>% pull(av.error)

# Print Results
c('Chain-Ladder' = size.error.cl, 'Hierarchical GLM' = size.error.hglm, 'Hierarchical GBM' = size.error.hgbm, 'Hierarchical XGB' = size.error.hxgb, 'Hierarchical DNN' = size.error.hdnn, 'Hierarchical CANN' = size.error.hcann)

```

```{r}
df.settle.error <- data.frame(
  name=c(rep("CL",100), rep("HGLM",100),rep("HGBM",100),rep("HXGB",100),rep("HDNN",100),rep("HCANN",100)) ,
  value=c(df.settle$error.cl, df.settle$error.hglm, df.settle$error.hgbm, 
          df.settle$error.hxgb, df.settle$error.hdnn, df.settle$error.hcann)
)

library(hrbrthemes)
library(ggplot2)
library(viridis)
df.settle.error %>%
  ggplot( aes(x=name, y=value, fill=name)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6, option="A") +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    ggtitle("Mean error boxplots for settlement") +
    xlab("")

```

```{r}
df.settle.error %>%
  ggplot( aes(x=name, y=value, fill=name)) +
    geom_violin() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6, option="A") +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    ggtitle("Mean error violinplots for settlement") +
    xlab("")
```

```{r}
df.pay.error <- data.frame(
  name=c(rep("CL",100), rep("HGLM",100),rep("HGBM",100),rep("HXGB",100),rep("HDNN",100),rep("HCANN",100)) ,
  value=c(df.pay$error.cl, df.pay$error.hglm, df.pay$error.hgbm, 
          df.pay$error.hxgb, df.pay$error.hdnn, df.pay$error.hcann)
)

library(hrbrthemes)
library(ggplot2)
library(viridis)
df.pay.error %>%
  ggplot( aes(x=name, y=value, fill=name)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6, option="A") +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    ggtitle("Mean error boxplots for payment") +
    xlab("")
```

```{r}
df.pay.error %>%
  ggplot( aes(x=name, y=value, fill=name)) +
    geom_violin() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6, option="A") +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    ggtitle("Mean error violinplots for payment") +
    xlab("")
```


```{r}
df.size.error <- data.frame(
  name=c(rep("CL",100), rep("HGLM",100),rep("HGBM",100),rep("HXGB",100),rep("HDNN",100),rep("HCANN",100)) ,
  value=c(df.size$error.cl, df.size$error.hglm, df.size$error.hgbm, 
          df.size$error.hxgb, df.size$error.hdnn, df.size$error.hcann)
)

library(hrbrthemes)
library(ggplot2)
library(viridis)
df.size.error %>%
  ggplot( aes(x=name, y=value, fill=name)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6, option="A") +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    ggtitle("Mean error boxplots for size") +
    xlab("")
```

```{r}
df.size.error %>%
  ggplot( aes(x=name, y=value, fill=name)) +
    geom_violin() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6, option="A") +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    ggtitle("Mean error violinplots for size") +
    xlab("")
```
